"""empty message

Revision ID: dbfe44b475cf
Revises: 
Create Date: 2022-11-05 17:27:57.897744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfe44b475cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('name', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
